# Generated by Django 4.2.16 on 2024-10-25 14:58

from django.db import migrations, models
import django_jsonform.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "permissies",
                    django_jsonform.models.fields.JSONField(
                        blank=True,
                        help_text="The permission this API token has access to.",
                        null=True,
                        verbose_name="permission",
                    ),
                ),
                (
                    "contact_persoon",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "telefoon_nummer",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Phonenumber of the person, who can access the API",
                        max_length=128,
                        region=None,
                        verbose_name="Phonenumber",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorization",
                "verbose_name_plural": "token authorizations",
            },
        ),
    ]
