# Generated by Django 4.2.16 on 2024-10-03 07:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "officiele_titel",
                    models.CharField(max_length=255, verbose_name="official title"),
                ),
                (
                    "verkorte_titel",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="short title"
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "registratiedatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="System timestamp reflecting when the publication was registered in the database. Not to be confused with the creation date of the publication, which is usually *before* the registration date.",
                        verbose_name="created on",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
            },
        ),
    ]
