# Generated by Django 4.2.16 on 2024-10-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The (primary) unique identifier.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "officiele_titel",
                    models.CharField(max_length=255, verbose_name="official title"),
                ),
                (
                    "verkorte_titel",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="short title"
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "creatiedatum",
                    models.DateField(
                        help_text="Date when the (physical) document came into existence. Not to be confused with the registration timestamp of the document - the creation date is typically *before* the registration date.",
                        verbose_name="creation date",
                    ),
                ),
                (
                    "bestandsformaat",
                    models.CharField(
                        default="unknown",
                        help_text="TODO - placeholder accepting anything, in the future this will be validated against a reference value list.",
                        max_length=255,
                        verbose_name="file format",
                    ),
                ),
                (
                    "bestandsnaam",
                    models.CharField(
                        default="unknown.bin",
                        help_text="File name 'on disk' of the document, e.g. 'gelakt-verslag.pdf'.",
                        max_length=255,
                        verbose_name="file name",
                    ),
                ),
                (
                    "bestandsomvang",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Size of the file on disk, in bytes.",
                        verbose_name="file size",
                    ),
                ),
                (
                    "registratiedatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="System timestamp reflecting when the publication was registered in the database. Not to be confused with the creation date of the publication, which is usually *before* the registration date.",
                        verbose_name="created on",
                    ),
                ),
                (
                    "publicatie",
                    models.ForeignKey(
                        help_text="The publication that this document belongs to. A publication may have zero or more documents.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.publication",
                        verbose_name="publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
    ]
