# Generated by Django 4.2.16 on 2024-10-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("publications", "0002_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_service",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zgw_consumers.service",
                verbose_name="Documents API Service",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="Document UUID"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("document_service", None), ("document_uuid", None)),
                    models.Q(
                        models.Q(("document_service", None), _negated=True),
                        models.Q(("document_uuid", None), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="document_api_conposite",
                violation_error_message="You must specify both the Document API Service and Document UUID to identify a document.",
            ),
        ),
    ]
