# Generated by Django 4.2.16 on 2024-10-25 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "publications",
            "0003_document_document_service_document_document_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="identifier",
            field=models.CharField(
                help_text="The (primary) unique identifier.",
                max_length=255,
                verbose_name="identifier",
            ),
        ),
    ]
