# Generated by Django 4.2.16 on 2024-10-25 07:38

from django.db import migrations, models
from django.db.migrations.state import StateApps
import uuid


def generate_unique_uuids(apps: StateApps, _):
    Document = apps.get_model("publications", "document")
    for document in Document.objects.all():
        document.uuid = uuid.uuid4()
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "publications",
            "0003_document_document_service_document_document_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="UUID"
            ),
        ),
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="identifier",
            field=models.CharField(
                help_text="The (primary) unique identifier.",
                max_length=255,
                verbose_name="identifier",
            ),
        ),
    ]
