# Generated by Django 4.2.16 on 2024-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_document_uuid_alter_document_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="lock",
            field=models.CharField(
                blank=True,
                help_text="The lock value to be able to update this document in the Documents API.",
                max_length=255,
                verbose_name="document lock",
            ),
        ),
    ]
