# Generated by Django 4.2.16 on 2024-11-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0005_document_lock"),
        ("publications", "0005_publication_informatie_categorieen"),
    ]

    operations = []
