# Generated by Django 4.2.16 on 2024-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0007_document_laatst_geweizigd_datum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="publicatiestatus",
            field=models.CharField(
                choices=[
                    ("gepubliceerd", "Published"),
                    ("concept", "Concept"),
                    ("ingetrokken", "Revoked"),
                ],
                default="gepubliceerd",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="publicatiestatus",
            field=models.CharField(
                choices=[
                    ("gepubliceerd", "Published"),
                    ("concept", "Concept"),
                    ("ingetrokken", "Revoked"),
                ],
                default="gepubliceerd",
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
