# Generated by Django 4.2.16 on 2024-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0009_document_publicatiestatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="The (primary) unique identifier.",
                max_length=255,
                verbose_name="identifier",
            ),
        ),
    ]
