# Generated by Django 4.2.16 on 2024-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0010_alter_document_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="soort_handeling",
            field=models.CharField(
                choices=[
                    ("ondertekening", "Signed"),
                    ("ontvangst", "Received"),
                    ("vaststelling", "Declared"),
                ],
                default="vaststelling",
                verbose_name="action type",
            ),
        ),
    ]
