# Generated by Django 4.2.16 on 2024-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0011_document_soort_handeling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="bestandsomvang",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Size of the file on disk, in bytes.",
                verbose_name="file size",
            ),
        ),
    ]
