# Generated by Django 4.2.16 on 2024-09-20 07:39

from django.db import migrations, models
import woo_publications.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationcategory",
            name="identifier",
            field=models.URLField(
                default=woo_publications.metadata.models.get_default_information_category_identifier,
                editable=False,
                help_text="The unique IRI that identifies this category in the overheid.nl value list. For entries that have been added manually, an identifier is generated.",
                max_length=255,
                unique=True,
                verbose_name="identifier",
            ),
        ),
    ]
