# Generated by Django 4.2.16 on 2024-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informatiecategorie",
            name="identifier",
            field=models.URLField(
                help_text="The unique URI that identifies this category in the overheid.nl value list. For entries that have been added manually, an identifier is generated.",
                max_length=255,
                unique=True,
                verbose_name="identifier",
            ),
        ),
    ]
