# Generated by Django 4.2.16 on 2024-09-20 13:01

from django.db import migrations, models
import woo_publications.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_alter_informationcategory_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "identifier",
                    models.URLField(
                        default=woo_publications.metadata.models.get_default_identifier,
                        editable=False,
                        help_text="The unique URI that identifies this theme in the overheid.nl value list. For entries that have been added manually, an identifier is generated.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="The name of the theme.",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                (
                    "publicatie_status_actief",
                    models.BooleanField(
                        default=False,
                        help_text="A flag to display if this theme is active or not.",
                        verbose_name="publication status active",
                    ),
                ),
                (
                    "oorsprong",
                    models.CharField(
                        choices=[
                            ("waardelijst", "Value list"),
                            ("zelf_toegevoegd", "Custom entry"),
                        ],
                        default="zelf_toegevoegd",
                        help_text="Determines where the theme is defined and sourced from, and how the identifier should be interpreted. If the value list is the origin, the theme can not be modified or deleted.",
                        max_length=15,
                        verbose_name="origin",
                    ),
                ),
            ],
            options={
                "verbose_name": "theme",
                "verbose_name_plural": "theme's",
            },
        ),
    ]
