# Generated by Django 4.2.16 on 2024-09-24 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0003_theme_alter_informationcategory_definitie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationcategory",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
