# Generated by Django 4.2.16 on 2024-10-22 12:02

from django.db import migrations, models
import uuid
import woo_publications.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0004_informationcategory_uuid_theme_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "identifier",
                    models.URLField(
                        default=woo_publications.metadata.models.get_default_organization_identifier,
                        editable=False,
                        help_text="The unique IRI that identifies this organisation in the overheid.nl value list. For entries that have been added manually, an identifier is generated.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                ("naam", models.CharField(max_length=80, verbose_name="name")),
                (
                    "oorsprong",
                    models.CharField(
                        choices=[
                            ("waardelijst", "Value list"),
                            ("zelf_toegevoegd", "Custom entry"),
                        ],
                        default="zelf_toegevoegd",
                        help_text="Determines where the organisation is defined and sourced from, and how the identifier should be interpreted. If the value list is the origin, the organisation can not be modified or deleted.",
                        max_length=15,
                        verbose_name="origin",
                    ),
                ),
                (
                    "is_actief",
                    models.BooleanField(
                        default=True,
                        help_text="Displays if the the organisation is currently active or not.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
            },
        ),
    ]
