# Generated by Django 4.2.16 on 2024-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0005_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="naam",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
