# Generated by Django 4.2.16 on 2024-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0006_alter_organisation_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="is_actief",
            field=models.BooleanField(
                default=False,
                help_text="Displays if the the organisation is currently active or not.",
                verbose_name="is active",
            ),
        ),
    ]
